# Generated by Django 2.2.7 on 2019-11-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatus',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
