# Generated by Django 2.2.7 on 2019-11-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='availble',
            new_name='available',
        ),
    ]
